// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2oiB2VOgitv4RUZWPGUOLsSdCi-fOLDw',
    appId: '1:635528833509:web:acd375b227ff8a55b6e70c',
    messagingSenderId: '635528833509',
    projectId: 'todo-vf',
    authDomain: 'todo-vf.firebaseapp.com',
    storageBucket: 'todo-vf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxtcXyx4DhC3dkwnpzWH6EW4XsZv3zgxc',
    appId: '1:635528833509:android:39cd7046c97528a4b6e70c',
    messagingSenderId: '635528833509',
    projectId: 'todo-vf',
    storageBucket: 'todo-vf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtrNWx-ZDdRTMtKEN11dyxD4NFoukSBs',
    appId: '1:635528833509:ios:5ac524e7fa5a4f2bb6e70c',
    messagingSenderId: '635528833509',
    projectId: 'todo-vf',
    storageBucket: 'todo-vf.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbtrNWx-ZDdRTMtKEN11dyxD4NFoukSBs',
    appId: '1:635528833509:ios:5ac524e7fa5a4f2bb6e70c',
    messagingSenderId: '635528833509',
    projectId: 'todo-vf',
    storageBucket: 'todo-vf.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2oiB2VOgitv4RUZWPGUOLsSdCi-fOLDw',
    appId: '1:635528833509:web:248b2ef0d6b7ef57b6e70c',
    messagingSenderId: '635528833509',
    projectId: 'todo-vf',
    authDomain: 'todo-vf.firebaseapp.com',
    storageBucket: 'todo-vf.firebasestorage.app',
  );
}
